# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout primary repo
      uses: actions/checkout@v2
      with:
        repository: opensha/opensha
        path: 'opensha'
    - name: Checkout dev repo
      uses: actions/checkout@v2
      with:
        path: 'opensha-dev'
    - name: Checkout cybershake repo
      uses: actions/checkout@v2
      with:
        path: 'opensha-cybershake'
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: opensha-cybershake
    - name: Build with Gradle
      run: ./gradlew assemble
      working-directory: opensha-cybershake
